package analizador;

import java.util.ArrayList;

public class Simbolo {
	public String programa = "";
	public boolean esPrograma = false;
	public String identificador = "";
	public boolean esIdentificador = false;
	public String empieza = "";
	public boolean esEmpieza = false;
	public String fin = "";
	public boolean esFin = false;
	public String constante = "";
	public boolean esConstante = false;
	public boolean esIdenoicador = false;
	public String igual = "";
	public boolean esIgual = false;
	public String puntocoma = "";
	public boolean esPuntocoma = false;
	public String numericoEnteroConstante = "";
	public boolean esNumericoEnteroConstante = false;
	public String variable = "";
	public boolean esVariable = false;
	public String abreParenteis = "";
	public boolean esAbreParenteis = false;
	public String cierraParentesis = "";
	public boolean esCierraParentesis = false;
	public String dosPuntos = "";
	public boolean esDosPuntos = false;
	public Object textoconstante = "";
	public boolean esTextoconstante = false;
	public String funcion = "";
	public boolean esFuncion = false;
	public String numericoRealConstante;
	public boolean esNumericoRealConstante;
	public String real;
	public boolean esReal = false;
	public String coma = "";
	public boolean esComa = false;
	public String procedimiento = "";
	public boolean esProcedimiento = false;
	public String mas = "";
	public boolean esMas = false;
	public String menos = "";
	public boolean esMenos = false;
	public String multiplica = "";
	public boolean esMultiplica = false;
	public String divide = "";
	public boolean esDivide = false;
	public String mod = "";
	public boolean esMod = false;
	public String punto = "";
	public boolean esPunto = false;
	public ArrayList<Simbolo> varLista;
	public ArrayList<Simbolo> tbas;
	public ArrayList<Simbolo> simpvalue;
	public ArrayList<Simbolo> devarlista;
	public ArrayList<Simbolo> proc_call;
	public ArrayList<Simbolo> asig;
	public ArrayList<Simbolo> subparamLista;
	public ArrayList<Simbolo> op;
	public ArrayList<Simbolo> exp;

}
