
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_PARENTESIS = 9;
  public static final int MOD = 21;
  public static final int PROCEDURE = 4;
  public static final int STRING_CONST = 19;
  public static final int MULTIPLICACION = 22;
  public static final int NUMERIC_INTEGER_CONST = 18;
  public static final int SEMICOLON = 11;
  public static final int PLUS = 23;
  public static final int EQUAL = 12;
  public static final int POINT = 17;
  public static final int END = 6;
  public static final int IDENTIFIER = 15;
  public static final int FUNCTION = 3;
  public static final int OPEN_PARENTESIS = 8;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 5;
  public static final int EOF = 0;
  public static final int POINT_SEMICOLON = 10;
  public static final int DIV = 24;
  public static final int MINUS = 25;
  public static final int CONST = 14;
  public static final int error = 1;
  public static final int NUMERIC_REAL_CONST = 16;
  public static final int END_COMENT = 26;
  public static final int DOUBLE_COLON = 13;
  public static final int VAR = 7;
  public static final int VACIO = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "FUNCTION",
  "PROCEDURE",
  "BEGIN",
  "END",
  "VAR",
  "OPEN_PARENTESIS",
  "CLOSE_PARENTESIS",
  "POINT_SEMICOLON",
  "SEMICOLON",
  "EQUAL",
  "DOUBLE_COLON",
  "CONST",
  "IDENTIFIER",
  "NUMERIC_REAL_CONST",
  "POINT",
  "NUMERIC_INTEGER_CONST",
  "STRING_CONST",
  "VACIO",
  "MOD",
  "MULTIPLICACION",
  "PLUS",
  "DIV",
  "MINUS",
  "END_COMENT"
  };
}

